import type { Metadata } from 'next'
import Reveal from '@/components/Reveal'
import { Btn, Caption, Rule } from '@/components/ui'
import { WHAT_WE_DO } from '@/config/content'

export const metadata: Metadata = { title: 'What We Do', description: 'Ano Global Holdings represents Chinese manufacturers across four supply verticals in African markets — energy and mobility, security systems, agriculture and food systems, and construction supply.', openGraph: { title: 'What We Do — Ano Global Holdings', description: 'Ano Global Holdings represents Chinese manufacturers across four supply verticals in African markets — energy and mobility, security systems, agriculture and food systems, and construction supply.', url: '/what-we-do', images: [{ url: '/og/what-we-do.png', width: 1200, height: 630, alt: 'What We Do — Ano Global Holdings' }] }, twitter: { card: 'summary_large_image', title: 'What We Do — Ano Global Holdings', description: 'Ano Global Holdings represents Chinese manufacturers across four supply verticals in African markets.', images: ['/og/what-we-do.png'] } }

export default function WhatWeDoPage() { return <>
  <section className="bg-bg pb-section pt-[132px] sm:pt-44 lg:pt-64"><div className="container-outer"><div className="content"><Reveal><h1 className="max-w-[18ch] text-h1">{WHAT_WE_DO.title}</h1><div className="measure mt-major space-y-6">{WHAT_WE_DO.intro.map(p=><p key={p} className="text-lead">{p}</p>)}</div></Reveal></div></div></section>
  <section className="bg-surface section"><div className="container-outer"><div className="content"><div className="grid gap-major md:grid-cols-2">{WHAT_WE_DO.verticals.map((v,i)=><Reveal key={v.title} delay={i*.05}><article className="h-full border-t border-line pt-8"><Caption>{String(i+1).padStart(2,'0')}</Caption><h2 className="mt-5 text-h2">{v.title}</h2><p className="measure mt-6 text-body">{v.body}</p><p className="caption mt-8">{v.status}</p>{v.href&&<div className="mt-6"><Btn href={v.href} accent="gold" external>anoenergy.com</Btn></div>}</article></Reveal>)}</div></div></div></section>
  <section className="bg-bg section"><div className="container-outer"><div className="content"><Reveal><div className="border-y border-line py-section"><h2 className="max-w-[18ch] text-h1">{WHAT_WE_DO.integrationHeading}</h2><div className="measure mt-major space-y-6">{WHAT_WE_DO.integration.map(p=><p key={p} className="text-lead">{p}</p>)}</div></div></Reveal><Reveal delay={.08} className="mt-section"><Rule/><h2 className="mt-8 text-h2">{WHAT_WE_DO.humanHeading}</h2><p className="measure mt-6 text-body">{WHAT_WE_DO.humanBody}</p><div className="mt-8"><Btn href="https://anocaresfoundation.org" accent="gold" external>anocaresfoundation.org</Btn></div></Reveal></div></div></section>
</> }
