import type { Metadata } from 'next'
import { Suspense } from 'react'
import EnquiryForm from '@/components/EnquiryForm'
import Reveal from '@/components/Reveal'
import { Btn, Caption, Rule } from '@/components/ui'
import { CONTACT } from '@/config/content'
import { SITE } from '@/config/site'

export const metadata: Metadata = { title: 'Contact', description: 'Contact Ano Global Holdings for energy, security, agriculture, construction, partnership, investment, institutional, foundation, speaking, and media enquiries.', openGraph: { title: 'Contact — Ano Global Holdings', description: 'Contact Ano Global Holdings for group-level, commercial, institutional, foundation, speaking, and media enquiries.', url: '/contact', images: [{ url: '/og/contact.png', width: 1200, height: 630, alt: 'Contact — Ano Global Holdings' }] }, twitter: { card: 'summary_large_image', title: 'Contact — Ano Global Holdings', description: 'Contact Ano Global Holdings for group-level, commercial, institutional, foundation, speaking, and media enquiries.', images: ['/og/contact.png'] } }

export default function ContactPage(){return <>
<section className="bg-bg pb-section pt-[132px] sm:pt-44 lg:pt-64"><div className="container-outer"><div className="content"><Reveal><h1 className="text-h1">{CONTACT.title}</h1><div className="mt-major"><p className="font-serif text-h2 text-heading">{CONTACT.org}</p><p className="mt-4 text-body"><a href={`mailto:${CONTACT.email}`} className="underline decoration-gold underline-offset-4">{CONTACT.email}</a></p></div></Reveal></div></div></section>
<section className="bg-surface section"><div className="container-outer"><div className="content"><Reveal><p className="measure text-lead">{CONTACT.intro}</p><div className="mt-major grid gap-major md:grid-cols-2">{[[CONTACT.energyHeading,CONTACT.energyBody,'https://anoenergy.com','anoenergy.com'],[CONTACT.securityHeading,CONTACT.securityBody,'/contact','Enquire here.'],[CONTACT.foundationHeading,CONTACT.foundationBody,'https://anocaresfoundation.org','anocaresfoundation.org'],[CONTACT.institutionalHeading,CONTACT.institutionalBody,'/contact','Enquire here.'],[CONTACT.speakingHeading,CONTACT.speakingBody,'/contact?enquiry=Speaking','Enquire here.']].map(([h,b,href,label])=><article key={h} className="border-t border-line pt-7"><h2 className="text-h2">{h}</h2><p className="measure mt-4 text-body">{b}</p><div className="mt-6"><Btn href={href} accent="gold" external={href.startsWith('http')}>{label}</Btn></div></article>)}</div></Reveal></div></div></section>
<section className="bg-bg section"><div className="container-outer"><div className="content"><Reveal><Rule/><h2 className="mt-8 text-h2">{CONTACT.formHeading}</h2><div className="mt-major"><Suspense fallback={null}><EnquiryForm/></Suspense></div></Reveal></div></div></section>
<section className="bg-surface section"><div className="container-outer"><div className="content"><Reveal><h2 className="text-h2">Contact</h2><p className="mt-6 text-body">Ano Global Holdings</p><a className="mt-2 block text-body underline decoration-gold underline-offset-4" href={`mailto:${SITE.email}`}>{SITE.email}</a><h2 className="mt-section text-h2">Locations</h2><p className="mt-6 text-body">New York · Hong Kong · Lagos</p><p className="mt-3 text-body">Registered office addresses are provided on request.</p><h2 className="mt-section text-h2">Group organizations</h2><div className="mt-6 grid gap-8 sm:grid-cols-2"><div><p className="font-semibold text-heading">Ano Energy</p><p className="caption mt-2">Energy · Infrastructure · Emerging Markets</p><a className="mt-2 block text-body underline decoration-gold underline-offset-4" href="https://anoenergy.com">anoenergy.com · contact@anoenergy.com</a></div><div><p className="font-semibold text-heading">Anosike Cares Foundation</p><p className="caption mt-2">Education · Youth · Global Opportunity</p><a className="mt-2 block text-body underline decoration-gold underline-offset-4" href="https://anocaresfoundation.org">anocaresfoundation.org · contact@anocaresfoundation.org</a></div></div></Reveal></div></div></section>
</>}
