import type { Metadata } from 'next'
import Reveal from '@/components/Reveal'
import { Caption, Rule } from '@/components/ui'
import { STRUCTURE } from '@/config/content'

export const metadata: Metadata = { title: 'Group Structure', description: 'Ano Global Holdings group structure, registered entities, and jurisdictions across Hong Kong and Nigeria.', openGraph: { title: 'Group Structure — Ano Global Holdings', description: 'Ano Global Holdings group structure, registered entities, and jurisdictions across Hong Kong and Nigeria.', url: '/structure', images: [{ url: '/og/structure.png', width: 1200, height: 630, alt: 'Group Structure — Ano Global Holdings' }] }, twitter: { card: 'summary_large_image', title: 'Group Structure — Ano Global Holdings', description: 'Ano Global Holdings group structure, registered entities, and jurisdictions across Hong Kong and Nigeria.', images: ['/og/structure.png'] } }
export default function StructurePage(){return <>
<section className="bg-bg pb-section pt-[132px] sm:pt-44 lg:pt-64"><div className="container-outer"><div className="content"><Reveal><Caption>Group structure and registered details</Caption><p className="measure mt-8 text-lead">{STRUCTURE.hero}</p><a className="mt-8 inline-block text-body underline decoration-gold underline-offset-4" href="https://anocaresfoundation.org">anocaresfoundation.org</a><h1 className="mt-section text-h1">{STRUCTURE.title}</h1><p className="measure mt-major text-body">{STRUCTURE.commercial}</p></Reveal></div></div></section>
<section className="bg-surface section"><div className="container-outer"><div className="content"><Reveal><div className="measure">{STRUCTURE.diagram.map((row,i)=><div key={row[0]} className="border-t border-line py-7"><div className={i?'pl-6 sm:pl-10':''}><h2 className={i?'font-display text-xl text-heading':'text-h2'}>{row[0]}</h2><p className="caption mt-2">{row[1]}</p>{row[2]&&<p className="mt-4 text-body">{row[2]}</p>}</div></div>)}</div></Reveal></div></div></section>
<section className="bg-bg section"><div className="container-outer"><div className="content"><Reveal><h2 className="text-h2">Registered entities</h2><div className="mt-major border-y border-line"><div className="py-7"><h3 className="text-body font-semibold">Ano Global Holdings</h3><p className="caption mt-2">Legal name and jurisdiction to be supplied by client · Holding company</p></div><div className="border-t border-line py-7"><h3 className="text-body font-semibold">Ano Energy Africa Limited</h3><p className="caption mt-2">Hong Kong</p></div></div><p className="measure mt-8 text-body">Full registration details, including registration numbers and registered addresses, are provided to counterparties, financial institutions, and development finance partners on request.</p></Reveal></div></div></section>
<section className="bg-bg section"><div className="container-outer"><div className="content"><Reveal><Rule/><h2 className="mt-8 text-h2">{STRUCTURE.twoEntitiesHeading}</h2><div className="measure mt-major space-y-6"><p className="text-body">{STRUCTURE.twoEntities}</p><p className="text-body">{STRUCTURE.twoEntities2}</p></div></Reveal><Reveal delay={.08} className="mt-section"><h2 className="text-h2">{STRUCTURE.chinaHeading}</h2><div className="measure mt-major space-y-6">{STRUCTURE.china.map(p=><p key={p} className="text-body">{p}</p>)}</div></Reveal><Reveal delay={.12} className="mt-section"><h2 className="text-h2">{STRUCTURE.operateHeading}</h2><div className="measure mt-major space-y-6">{STRUCTURE.operate.map(p=><p key={p} className="text-body">{p}</p>)}</div></Reveal></div></div></section>
</>}
